version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "testValue"
phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  build:
    commands:
     - echo Build started on `date`
     - gradle build
artifacts:
  name: hello-dev-jar
  type: zip
  location: app/src/main/java/Hello/dev/App.class
 
